### ISSUE TITLE
缺少setup.py文件

### ISSUE THREAD

**Issue by shouzheng** [pyloong/cookiecutter-pythonic-project#21]
因为缺少setup.py文件，无法执行`python setup.py sdist bdist_wheel`命令。

文档和模板不匹配？

参考文档地址：[快速上手 - 打包](https://pyloong.github.io/pythonic-project-guidelines/quick_start/#251)

**Comment by whg517** [comment]
感谢你提出的问题，对于这个问题当前已经修复。我们在最近根据新的技术动态调整了项目模板，并开始着手同步调整工程化指南中的文档。
